title: marcofromsicily Blog
description: Marketing & Open Source
url: http://www.marcolombardo.com/blog/
baseurl: /blog
author: Marco Lombardo
email: mail@marcolombardo.com

twitter_username: marcofromsicily
linkedin_username: marcofromsicily
github_username:  marcofromsicily

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

gems:
    - jekyll-seo-tag
    - jekyll-sitemap
